version: "3"
services:
  flora-server:
    build: .
    container_name: flora-server-dev-env
    ports:
      - "8084:8084"
    volumes:
      - database-data:/flora-server/pgdata/
      - .:/flora-server:Z
    links:
      - database

  database:
    # Pinned postgres:14.7
    image: "postgres@sha256:577d48a963bdd16e8b93e853aa830c78fc4622ebe9717bc95f6736d9aa5003e3"
    container_name: database
    ports:
      - "5432:5432"
    expose:
      - "5432"
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data    
volumes:
  database-data:
